version: '2'

services:
  dev:
    build: .
    image: turbasen.py
    working_dir: /app
    volumes:
    - .:/app
    env_file: .env
    environment:
      ENDPOINT_URL: https://dev.nasjonalturbase.no
